// lib/seed.ts — the offline catalog (issue #4).
//
// seed.json is generated by `node scripts/curate.mjs` and committed. Importing
// it bundles the catalog into the app, so the deck still fills when the venue
// Wi-Fi dies — PLAN.md §L rates that the highest likelihood/impact risk. The
// TMDB fetch layer (#15) falls back to these exact objects.

import type { Movie, VideoSource } from '@/types';
import rawSeed from './seed.json';

// JSON imports widen `source` to `string`, so narrow it once here rather than
// casting the whole array — that way a genuinely wrong field still fails to
// compile instead of being waved through.
export const seedMovies: Movie[] = rawSeed.map((movie) => ({
  ...movie,
  video: movie.video
    ? { ...movie.video, source: movie.video.source as VideoSource }
    : null,
}));

/** Movies whose YouTube key passed validation — the only ones that can autoplay. */
export const seedMoviesWithVideo: Movie[] = seedMovies.filter((movie) => movie.video !== null);
